### ISSUE TITLE
Pixy2 and panError

### ISSUE THREAD

**Issue by paddygoat** [paddygoat/WEEDINATOR#14]
@SlashDevin  I've been trying to get the Pixy2 up and running, but the vector info does not seem to reach the TC275. I'm not sure why this is, or if it's because the machine is stationary or not - it's difficult to test if the machine is moving!

I suggest that we transmit a variable called 'panError' from the Mega to TC275 which will make all the code much clearer with no need to use the term 'compass' anymore. panError describes the amount that the steering needs to rotate to correct the perceived error in direction of travel. In terms of GPS navigation, it's equivalent to (heading - bearing).

I suppose now would be the time to also activate the 'use GPS' command which will look like this: "GPS", "PIXY" and "JETSON" from the hdgSrc column in the database.

For now, the data will look like this: LAT533027200LONG-42398365PIXY

By the way, I don't see any current use for the compass module, so it can be completely de-activated. 

Thanks!

**Comment by SlashDevin** [comment]
The Pixy panError variable is now transmitted from the Mega to the TC275.  You need to decide what to do with it in TC275.ino.  You can grab the `panError` value out of the `navData message [here](https://github.com/paddygoat/WEEDINATOR/blob/master/platforms/TC275/TC275.ino#L957).  I assume that it needs to go in a global variable, like the other values.
